config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/auth/:provider/callback', to: 'session#create'
  get '/recommendation_results', to: 'session#results'

end

app/models/graph.rb
class Graph < ActiveRecord::Base
  validates :src_tag, presence: true, length: { maximum: 100 }
  validates :dest_tag, presence: true, length: { maximum: 100 }
  validates :upvotes, numericality: { greater_than_or_equal_to: 0 }

  def Graph.add_edge(src_tag, dest_tag, upvotes)
    edge = find_by(src_tag: src_tag, dest_tag: dest_tag)
    if edge
        edge.update(upvotes: edge.upvotes + upvotes)
    else
      create(src_tag: src_tag, dest_tag: dest_tag, upvotes: upvotes)
    end
  end

  def Graph.upvotes_for_src(src_tag)
    self.where("src_tag = ? and dest_tag != ?", src_tag, src_tag).order(upvotes: :desc)
  end

  def Graph.upvotes_for_tags(src_tag, dest_tag)
    self.where("src_tag = ? and dest_tag = ?", src_tag, dest_tag).first
  end

  def Graph.relevant_question_rows(user_tags, qtag)
    self.where("dest_tag = ? and src_tag in (?)", qtag, user_tags)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/session_controller.rb
require 'cgi'
require 'uri'
require './lib/magicblackbox/MagicBlackBoxParameters'
require './lib/magicblackbox/MagicBlackBox'
require './lib/stackexchange/stackapi'

class SessionController < ApplicationController
  def create

    uri = URI.parse(request.url)
    params = CGI.parse(uri.query)
    params[:client_id] = ENV['CLIENT_ID']
    params[:client_secret] = ENV['CLIENT_SECRET']
    params[:redirect_uri] = 'https://serloin.herokuapp.com/auth/stackoverflow/callback'
    uri = URI.parse('https://stackexchange.com')
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    post_requ = Net::HTTP::Post.new("/oauth/access_token")
    post_requ.add_field('Content-Type', 'application/x-www-form-urlencoded')
    post_requ.set_form_data(params)
    @response = http.request(post_requ)

    if Integer(@response.code) != 200
      flash[:danger] = "There was an error authenticating with Stack Exchange"
      redirect_to root_url
    end

    session[:access_token] = @response.body.split('=')[1]
  end

  def results
    requ_builder = StackExchangeRequestBuilder.new(access_token: session[:access_token], app_key: ENV['CLIENT_KEY'])
    user_info = requ_builder.current_user_info()
    @recent_questions = requ_builder.most_recent_questions()

    currentTime = Time.now.to_i
    @questionList = Hash.new
    @recent_questions.each do |question|
      magicBlackBoxParameters = MagicBlackBoxParameters.new(user_info, question,
        MagicBlackBoxAdjacencyGraphData.new(user_info, question), currentTime)
      @questionList[question.questionId] = MagicBlackBox.new(magicBlackBoxParameters).runBlackBox()
    end
    @sorted_questions = @questionList.sort_by {|id,tuple| -tuple[0]}
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @oauth_url = "https://stackexchange.com/oauth?client_id=8577&redirect_uri=https%3A%2F%2Fserloin.herokuapp.com%2Fauth%2Fstackoverflow%2Fcallback&response_type=code&scope=no_expiry&state=23637e859ceb0de3b44099350b9b278ee741c3b1091b3ec0"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "SERLOIN"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/session_helper.rb
module SessionHelper
  def find_question(recent_questions, id)
    recent_questions.each do |question|
      if question.questionId == id
        return question
      end
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    SERLOIN
  </small>
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'SERLOIN', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">

      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/session/create.html.erb
<% provide(:title, "Create Session") %>

<div class="jumbotron" style="text-align:center;">
  <h2>You were successfully authenticated to Stack Exchange!</h2>
  <%= link_to "Get Recommendations", recommendation_results_path, class: "btn btn-primary", id: "recommend-btn" %>
</div>

<div id="waiting-div" class="row text-center" style="display:none;">
  </br>
  <i id="waiting-spinner" class="fa fa-gear fa-spin"></i>
  <h2>Recommending questions to answer...</h2>
</div>

app/views/session/results.html.erb
<% provide(:title, "Results") %>
<h1>Here are your results!</h1>

<% @sorted_questions.each do |question| %>
  <% full_question = find_question(@recent_questions, question[0]) %>
  <p><%= link_to "#{full_question.title} (#{question[0]})", "https://stackoverflow.com/questions/#{question[0]}" %>
    <br>
    <b style="color:#228B22">Question Tags: <%= full_question.tagsSet.inspect %></b>
    <br>
    Relevance: <%= @questionList[question[0]] %>
  </p>
  <hr>
<% end %>

<!--<h2><%= @recent_questions.inspect %></h2>
<h2><%= @sorted_questions.inspect %></h2>-->

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="jumbotron">
  <h1>Welcome!</h1>
  <%= image_tag "sirloin-steak.png", class: "center-block", size: "300x215" %>
  <h2>Authenticate to <%= link_to 'Stack Exchange', @oauth_url %> to get started.</h2>
</div>

<!--<div class="row">
  <%= image_tag "sirloin-steak.png", class: "center-block", size: "300x215" %>

  <h1>SERLOIN</h1>

  <label for="userID">Please enter your StackOverflow user ID</label>
  <input type="text" class="form-control" id="userID" placeholder="StackOverflow User ID">
  </br>
  <button type="button" class="btn btn-primary" id="submit-btn">Submit</button>

</div>

<div id="waiting-div" class="row text-center" style="display:none;">
  </br>
  <i id="waiting-spinner" class="fa fa-gear fa-spin"></i>
  <h2>Fetching results</h2>
</div>-->